// REGISTER
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "admin 3",
    "email": "admin3@gmail.com",
    "password": "123456",
    "confirmPassword": "123456",
    "role": "admin"
}


// ADD Keluarga
POST http://localhost:5000/keluarga
Content-Type: application/json

{
    "name": "Keluarga 1",
}

####
// ADD USER
POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "admin 3",
    "email": "admin3@gmail.com",
    "password": "123456",
    "confirmPassword": "123456",
    "role": "user"
}

###
// GET ALL USER
GET http://localhost:5000/user

###
// GET USER BY ID
GET http://localhost:5000/user/3c059912-3bd7-461c-aeba-69e30e0b9ba7


GET http://localhost:5000/keluarga/keluarga-1




###
// UPDATE USER
PATCH  http://localhost:5000/user/075878c4-a162-496f-831a-4ffa107c3f42
Content-Type: application/json

{
    "name": "anak 1 update",
    "email": "anak1@gmail.com",
    "password": "",
    "confirmPassword": "",
    "role": "user"
}

###
// DELETE USER
DELETE http://localhost:5000/user/636da70b-1f4f-48f6-9ca3-31584eb58537



###
// LOGIN ADMIN
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ibu@gmail.com",
    "password": "123456"
}

###
// LOGIN USER
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "anak@gmail.com",
    "password": "123456"
}

###
// ME
GET http://localhost:5000/me

###
// LOGOUT
DELETE  http://localhost:5000/logout

########################
//POST TUGAS
POST http://localhost:5000/tugas
Content-Type: application/json

{
"judul": "tugas 2",
"deskripsi": "berdoa sebelum makan",
"point": 100
}

###
// GET ALL TUGAS
GET http://localhost:5000/tugas

###
// GET SINGLE TUGAS
GET http://localhost:5000/tugas/eed84588-7416-40eb-986f-aaf5295d39fd

###
// UPDATE TUGAS
PATCH  http://localhost:5000/tugas/eed84588-7416-40eb-986f-aaf5295d39fd
Content-Type: application/json

{
    "judul": "tugas ayah",
    "deskripsi": "tugas 6 update",
    "point": 100
}

###
// DELETE TUGAS
DELETE http://localhost:5000/tugas/4eafa822-87e8-49d2-b53c-e7471dad2ea9


###
// GET ALL SUBMIT
GET http://localhost:5000/submit

###
// GET SINGLE SUBMIT
GET http://localhost:5000/submit/dsgfagfsa

########################
//POST SUBMIT TUGAS
POST http://localhost:5000/submit/019274d2-2d60-4b48-810f-6aa0d3e9b43f
Content-Type: application/json

{
    "komentar": "berdoa sudah 2",
    "file": "bukti berdoa 2",
}

